name: agentfem-learning-dev
channels:
  - conda-forge
dependencies:
  - python=3.11
  - fenics-dolfinx
  - mpich
  - mpi4py
  - petsc4py
  - h5py
  - numpy
  - pytorch
  - pip
  - pip:
      - build
      - pytest>=8
      - ruff>=0.16,<0.17
      - twine
